### ISSUE TITLE
Microsoft.Kernel Memory.Search.SearchClient[0] No memories a

### ISSUE THREAD

**Issue by DDT88** [marcominerva/KernelMemoryService#6]
Hi, 
i clone the repository and I insert the my configuration ( azureOpenAI) and storage, vector and queue (Local Disk).
I load the document (docx) and i recived always the response **warn: Microsoft.KernelMemory.Search.SearchClient[0]
      No memories available** , why ? 

Thanks

**Comment by marcominerva** [comment]
What parameters are you using when invoking the **ask** endpoint?

**Comment by DDT88** [comment]
Thanks :)
